# Generated by Django 2.2.3 on 2019-09-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='used',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO')], default=0),
        ),
    ]
