# Generated by Django 2.2.3 on 2019-09-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_userinfo_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='used',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO')], default=0, verbose_name='使用'),
        ),
    ]
