# Generated by Django 2.2.3 on 2019-09-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0004_auto_20190926_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='location',
            field=models.CharField(default='china', max_length=30, verbose_name='地理位置'),
            preserve_default=False,
        ),
    ]
