# Generated by Django 2.2.3 on 2019-11-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0005_userinfo_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(max_length=200, upload_to='media/userinfo_image/', verbose_name='头像'),
        ),
    ]
