# Generated by Django 2.2.3 on 2019-08-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=10, verbose_name='IP地址')),
                ('ip_addr', models.CharField(default='', max_length=100, verbose_name='IP地理位置')),
                ('count', models.IntegerField(default=0, verbose_name='访问次数')),
            ],
            options={
                'verbose_name': '用户访问信息',
                'verbose_name_plural': '用户访问信息',
            },
        ),
    ]
