# Generated by Django 2.2.3 on 2019-08-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_statistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userip',
            name='ip',
            field=models.CharField(max_length=50, unique=True, verbose_name='IP地址'),
        ),
    ]
