# Generated by Django 2.2.3 on 2019-08-14 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_statistics', '0002_auto_20190814_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterviewInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_time', models.DateTimeField(auto_now_add=True, verbose_name='访问时间')),
                ('interview_url', models.CharField(default='', max_length=100, verbose_name='访问地址')),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_statistics.UserIP', verbose_name='用户IP地址')),
            ],
        ),
    ]
