# Generated by Django 2.2.3 on 2019-08-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfileinfo',
            name='size',
            field=models.IntegerField(blank=True, null=True, verbose_name='文件大小'),
        ),
        migrations.AddField(
            model_name='uploadfileinfo',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='上传时间'),
        ),
    ]
